# Generated by Django 6.0.3 on 2026-03-08 14:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_alter_sensordata_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='on',
            field=models.BooleanField(default=False, verbose_name='Включен'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя датчика'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='unit',
            field=models.CharField(max_length=20, verbose_name='Ед. изм.'),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='sensors.sensor', verbose_name='Сенсор'),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время измерения'),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='value',
            field=models.FloatField(verbose_name='Значение'),
        ),
    ]
