# Generated by Django 6.0.3 on 2026-03-08 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_sensor_on_alter_sensor_name_alter_sensor_unit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensor',
            options={'ordering': ['name'], 'verbose_name': 'Датчик', 'verbose_name_plural': 'Датчики'},
        ),
        migrations.AlterModelOptions(
            name='sensordata',
            options={'get_latest_by': 'timestamp', 'ordering': ['timestamp'], 'verbose_name': 'Измерение', 'verbose_name_plural': 'Измерения'},
        ),
    ]
