# Generated by Django 6.0.3 on 2026-03-08 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0004_alter_sensor_options_alter_sensordata_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='interval',
            field=models.IntegerField(default=10, verbose_name='Интервал опроса'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='max_value',
            field=models.FloatField(default=100, verbose_name='Максимальное значение'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='min_value',
            field=models.FloatField(default=0, verbose_name='Минимальное значение'),
        ),
    ]
