# Generated by Django 6.0.3 on 2026-03-09 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0005_sensor_interval_sensor_max_value_sensor_min_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='threshold_above',
            field=models.FloatField(blank=True, null=True, verbose_name='Верхний порог'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='threshold_below',
            field=models.FloatField(blank=True, null=True, verbose_name='Нижний порог'),
        ),
    ]
